"""Table update

Revision ID: 8c24a0fbf160
Revises: 895b2eb7cea2
Create Date: 2026-01-22 15:59:18.496601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c24a0fbf160'
down_revision: Union[str, Sequence[str], None] = '895b2eb7cea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'firstname',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('clients', 'lastname',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('clients', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('clients', 'added_by',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('conference_room_av_equipment', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('conference_room_av_equipment', 'ip_address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('conference_room_av_equipment', 'mac_address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('connection_type', 'ctype_description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('cpu_type', 'cpu_type_description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('devices', 'category',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('devices', 'brand',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('devices', 'model',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('devices', 'serial_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('division', 'division_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('laptop', 'hard_disk_capacity',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('laptop', 'memory_capacity',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('laptop', 'processor_speed',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('laptop', 'processor_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('laptop', 'computer_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('laptop', 'mac_address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('laptop', 'operating_system',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('laptop', 'microsoft_office_version',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('laptop', 'antivirus',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('laptop', 'pdf_reader',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('location', 'location_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('location', 'added_by',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('location_type', 'ltype_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('parish', 'parish_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('printer', 'ip_address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('printer', 'feature_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('printer', 'connection_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('printer_feature', 'feature_description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('roles', 'role_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('roles', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('system_status', 'status_description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tablet', 'imei_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tablet', 'operating_system',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tablet', 'version',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tablet', 'hard_disk_capacity',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tablet', 'memory_capacity',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tablet', 'memory_capacity',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tablet', 'hard_disk_capacity',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tablet', 'version',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tablet', 'operating_system',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tablet', 'imei_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('system_status', 'status_description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('roles', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('roles', 'role_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('printer_feature', 'feature_description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('printer', 'connection_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('printer', 'feature_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('printer', 'ip_address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('parish', 'parish_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('location_type', 'ltype_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('location', 'added_by',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('location', 'location_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('laptop', 'pdf_reader',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('laptop', 'antivirus',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('laptop', 'microsoft_office_version',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('laptop', 'operating_system',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('laptop', 'mac_address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('laptop', 'computer_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('laptop', 'processor_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('laptop', 'processor_speed',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('laptop', 'memory_capacity',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('laptop', 'hard_disk_capacity',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('division', 'division_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('devices', 'serial_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('devices', 'model',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('devices', 'brand',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('devices', 'category',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('cpu_type', 'cpu_type_description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('connection_type', 'ctype_description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('conference_room_av_equipment', 'mac_address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('conference_room_av_equipment', 'ip_address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('conference_room_av_equipment', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('clients', 'added_by',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('clients', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('clients', 'lastname',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('clients', 'firstname',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
