"""Initial migration

Revision ID: a52c03a45b4c
Revises: 
Create Date: 2025-11-27 16:24:51.633006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a52c03a45b4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('devices_id', sa.Integer(), nullable=True),
    sa.Column('parish_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('ltype_id', sa.Integer(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.Column('added_by', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_clients_client_id'), 'clients', ['client_id'], unique=False)
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('devices_id', sa.Integer(), nullable=True),
    sa.Column('comment_value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_comments_comment_id'), 'comments', ['comment_id'], unique=False)
    op.create_table('connection_type',
    sa.Column('ctype_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ctype_description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('ctype_id')
    )
    op.create_index(op.f('ix_connection_type_ctype_id'), 'connection_type', ['ctype_id'], unique=False)
    op.create_table('cpu_type',
    sa.Column('cpu_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpu_type_description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('cpu_type_id')
    )
    op.create_index(op.f('ix_cpu_type_cpu_type_id'), 'cpu_type', ['cpu_type_id'], unique=False)
    op.create_table('location_type',
    sa.Column('ltype_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ltype_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('ltype_id')
    )
    op.create_index(op.f('ix_location_type_ltype_id'), 'location_type', ['ltype_id'], unique=False)
    op.create_table('parish',
    sa.Column('parish_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parish_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('parish_id')
    )
    op.create_index(op.f('ix_parish_parish_id'), 'parish', ['parish_id'], unique=False)
    op.create_table('printer_feature',
    sa.Column('feature_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feature_description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('feature_id')
    )
    op.create_index(op.f('ix_printer_feature_feature_id'), 'printer_feature', ['feature_id'], unique=False)
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_roles_role_id'), 'roles', ['role_id'], unique=False)
    op.create_table('system_status',
    sa.Column('status_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status_description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('status_id')
    )
    op.create_index(op.f('ix_system_status_status_id'), 'system_status', ['status_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('location',
    sa.Column('location_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('parish_id', sa.Integer(), nullable=True),
    sa.Column('added_by', sa.String(length=255), nullable=False),
    sa.Column('date_added', sa.Date(), nullable=True),
    sa.Column('ltype_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parish_id'], ['parish.parish_id'], ),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_index(op.f('ix_location_location_id'), 'location', ['location_id'], unique=False)
    op.create_table('division',
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('division_name', sa.String(length=255), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('added_by', sa.String(length=255), nullable=False),
    sa.Column('date_added', sa.Date(), nullable=True),
    sa.Column('devices_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], ),
    sa.PrimaryKeyConstraint('division_id')
    )
    op.create_index(op.f('ix_division_division_id'), 'division', ['division_id'], unique=False)
    op.create_table('devices',
    sa.Column('devices_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('inventory_number', sa.Integer(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('deployment_date', sa.Date(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('added_by', sa.String(length=255), nullable=True),
    sa.Column('last_updated_by', sa.String(length=255), nullable=True),
    sa.Column('repaired_date', sa.Date(), nullable=True),
    sa.Column('repaired_by', sa.String(length=255), nullable=True),
    sa.Column('bos_date', sa.Date(), nullable=True),
    sa.Column('bos_by', sa.String(length=255), nullable=True),
    sa.Column('deployed_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['division.division_id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['system_status.status_id'], ),
    sa.PrimaryKeyConstraint('devices_id'),
    sa.UniqueConstraint('model')
    )
    op.create_index(op.f('ix_devices_devices_id'), 'devices', ['devices_id'], unique=False)
    op.create_table('conference_room_av_equipment',
    sa.Column('cr_equipment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=255), nullable=False),
    sa.Column('mac_address', sa.String(length=255), nullable=False),
    sa.Column('devices_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['devices_id'], ['devices.devices_id'], ),
    sa.PrimaryKeyConstraint('cr_equipment_id')
    )
    op.create_index(op.f('ix_conference_room_av_equipment_cr_equipment_id'), 'conference_room_av_equipment', ['cr_equipment_id'], unique=False)
    op.create_table('laptop',
    sa.Column('laptop_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpu_type_id', sa.Integer(), nullable=False),
    sa.Column('hard_disk_capacity', sa.String(length=255), nullable=False),
    sa.Column('memory_capacity', sa.String(length=255), nullable=False),
    sa.Column('processor_speed', sa.String(length=255), nullable=False),
    sa.Column('processor_type', sa.String(length=255), nullable=False),
    sa.Column('computer_name', sa.String(length=255), nullable=False),
    sa.Column('mac_address', sa.String(length=255), nullable=False),
    sa.Column('operating_system', sa.String(length=255), nullable=False),
    sa.Column('microsoft_office_version', sa.String(length=255), nullable=False),
    sa.Column('antivirus', sa.String(length=255), nullable=False),
    sa.Column('pdf_reader', sa.String(length=255), nullable=False),
    sa.Column('warranty_start_date', sa.Date(), nullable=True),
    sa.Column('warranty_end_date', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('devices_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['devices_id'], ['devices.devices_id'], ),
    sa.PrimaryKeyConstraint('laptop_id')
    )
    op.create_index(op.f('ix_laptop_laptop_id'), 'laptop', ['laptop_id'], unique=False)
    op.create_table('mouse_keyboard',
    sa.Column('mouse_keyboard_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connection_type_id', sa.Integer(), nullable=False),
    sa.Column('devices_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['devices_id'], ['devices.devices_id'], ),
    sa.PrimaryKeyConstraint('mouse_keyboard_id')
    )
    op.create_index(op.f('ix_mouse_keyboard_mouse_keyboard_id'), 'mouse_keyboard', ['mouse_keyboard_id'], unique=False)
    op.create_table('printer',
    sa.Column('printer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.String(length=255), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('connection_type_id', sa.Integer(), nullable=False),
    sa.Column('devices_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['devices_id'], ['devices.devices_id'], ),
    sa.PrimaryKeyConstraint('printer_id')
    )
    op.create_index(op.f('ix_printer_printer_id'), 'printer', ['printer_id'], unique=False)
    op.create_table('tablet',
    sa.Column('tablet_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('imei_number', sa.String(length=255), nullable=False),
    sa.Column('operating_system', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=False),
    sa.Column('hard_disk_capacity', sa.String(length=255), nullable=False),
    sa.Column('memory_capacity', sa.String(length=255), nullable=False),
    sa.Column('warranty_start_date', sa.Date(), nullable=True),
    sa.Column('warranty_end_date', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('devices_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['devices_id'], ['devices.devices_id'], ),
    sa.PrimaryKeyConstraint('tablet_id')
    )
    op.create_index(op.f('ix_tablet_tablet_id'), 'tablet', ['tablet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tablet_tablet_id'), table_name='tablet')
    op.drop_table('tablet')
    op.drop_index(op.f('ix_printer_printer_id'), table_name='printer')
    op.drop_table('printer')
    op.drop_index(op.f('ix_mouse_keyboard_mouse_keyboard_id'), table_name='mouse_keyboard')
    op.drop_table('mouse_keyboard')
    op.drop_index(op.f('ix_laptop_laptop_id'), table_name='laptop')
    op.drop_table('laptop')
    op.drop_index(op.f('ix_conference_room_av_equipment_cr_equipment_id'), table_name='conference_room_av_equipment')
    op.drop_table('conference_room_av_equipment')
    op.drop_index(op.f('ix_devices_devices_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_division_division_id'), table_name='division')
    op.drop_table('division')
    op.drop_index(op.f('ix_location_location_id'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_status_status_id'), table_name='system_status')
    op.drop_table('system_status')
    op.drop_index(op.f('ix_roles_role_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_printer_feature_feature_id'), table_name='printer_feature')
    op.drop_table('printer_feature')
    op.drop_index(op.f('ix_parish_parish_id'), table_name='parish')
    op.drop_table('parish')
    op.drop_index(op.f('ix_location_type_ltype_id'), table_name='location_type')
    op.drop_table('location_type')
    op.drop_index(op.f('ix_cpu_type_cpu_type_id'), table_name='cpu_type')
    op.drop_table('cpu_type')
    op.drop_index(op.f('ix_connection_type_ctype_id'), table_name='connection_type')
    op.drop_table('connection_type')
    op.drop_index(op.f('ix_comments_comment_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_clients_client_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
